let data = {
  name: "Collect",
  step: 0,
  branch_type: "trunk",
  ppl: 1,
  time: 20,
  type: "pax_collect",
  children: [
    {
      name: "Translate",
      step: 1,
      branch_type: "trunk",
      ppl: 25,
      time: 10,
      type: "pax_translate",
      children: [
        {
          name: "Transcribe",
          step: 2,
          branch_type: "trunk",
          ppl: 1,
          time: 40,
          type: "pax_transcribe",
          children: [
            {
              name: "Code",
              step: 3,
              branch_type: "trunk",
              ppl: 40,
              time: 100,
              type: "pax_code",
              link: "https://pax.peaceagreements.org/media/documents/PA_X_codebook_v8.pdf",
              children: [
                {
                  name: "Quality Control",
                  step: 4,
                  branch_type: "trunk",
                  ppl: 7,
                  time: 20,
                  type: "pax_quality_control",
                  children: [
                    {
                      name: "PA-X",
                      step: 5,
                      branch_type: "trunk",
                      ppl: 3,
                      time: 100,
                      type: "pax_db",
                      link: "https://pax.peaceagreements.org/agreements/search/",
                      children: [
                        {
                          name: "Research",
                          step: 9,
                          branch_type: "uppest_trunk",
                          ppl: 50,
                          time: 100,
                          type: "research",
                          children: [
                            {
                              name: "paper",
                              step: 10,
                              branch_type: "leaf",
                              ppl: 3,
                              time: 10,
                              type: "data_report",
                            },
                            {
                              name: "paper",
                              step: 10,
                              branch_type: "leaf",
                              ppl: 1,
                              time: 10,
                              type: "book",
                            },
                            {
                              name: "paper",
                              step: 10,
                              branch_type: "leaf",
                              ppl: 1,
                              time: 10,
                              type: "journal",
                            },
                            {
                              name: "paper",
                              step: 10,
                              branch_type: "leaf",
                              ppl: 1,
                              time: 10,
                              type: "blog",
                            },
                            {
                              name: "paper",
                              step: 10,
                              branch_type: "leaf",
                              ppl: 1,
                              time: 10,
                              type: "conference",
                            },
                          ],
                        },
                        {
                          name: "Code",
                          step: 6,
                          branch_type: "upper_trunk",
                          ppl: 13,
                          time: 50,
                          type: "pax_gender_code",
                          link: "https://pax.peaceagreements.org/media/documents/PA_X_codebook_wgg_v8.pdf",
                          children: [
                            {
                              name: "Quality Control",
                              step: 7,
                              branch_type: "upper_trunk",
                              ppl: 7,
                              time: 20,
                              type: "pax_gender_quality_control",
                              children: [
                                {
                                  name: "PA-X Gender",
                                  step: 8,
                                  branch_type: "upper_trunk",
                                  ppl: 3,
                                  time: 10,
                                  type: "pax_gender_db",
                                  link: "https://pax.peaceagreements.org/agreements/wggsearch/",
                                  children: [
                                    {
                                      name: "App Development",
                                      step: 11,
                                      branch_type: "uppest_trunk",
                                      ppl: 2,
                                      time: 10,
                                      type: "prog",
                                      children: [
                                        {
                                          name: "PeaceFem",
                                          step: 12,
                                          branch_type: "leaf",
                                          ppl: 4,
                                          time: 2,
                                          type: "app",
                                          link: "https://peacerep.org/digital-resources/peacefem/",
                                        },
                                      ]
                                    },
                                    {
                                      name: "d3",
                                      step: 11,
                                      branch_type: "uppest_trunk",
                                      ppl: 1,
                                      time: 3,
                                      type: "prog",
                                      link: "https://github.com/tvancisin/pax_gender",
                                      children: [
                                        {
                                          name: "Scrollytelling",
                                          step: 12,
                                          ppl: 4,
                                          time: "2",
                                          type: "vis",
                                          link: "https://tvancisin.github.io/pax_gender/",
                                        },
                                      ],
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Code",
                          step: 6,
                          branch_type: "upper_trunk",
                          ppl: 2,
                          time: 100,
                          type: "pax_children_code",
                          children: [
                            {
                              name: "Quality Control",
                              step: 7,
                              branch_type: "upper_trunk",
                              ppl: 7,
                              time: 20,
                              type: "pax_children_quality_control",
                              children: [
                                {
                                  name: "Children & Youth",
                                  step: 8,
                                  branch_type: "upper_trunk",
                                  ppl: 3,
                                  time: 10,
                                  type: "pax_children_db",
                                  children: [
                                    {
                                      name: "PBi Youth Development",
                                      step: 11,
                                      branch_type: "uppest_trunk",
                                      ppl: 1,
                                      time: 10,
                                      type: "prog",
                                      children: [{
                                        name: "PBi Youth",
                                        step: 12,
                                        branch_type: "leaf",
                                        ppl: 1,
                                        time: 1,
                                        type: "vis",
                                      }]
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Code",
                          step: 6,
                          branch_type: "upper_trunk",
                          ppl: 10,
                          time: 100,
                          type: "pax_local_code",
                          children: [
                            {
                              name: "Quality Control",
                              step: 7,
                              branch_type: "upper_trunk",
                              ppl: 7,
                              time: 20,
                              type: "pax_local_quality_control",
                              children: [
                                {
                                  name: "PA-X Local",
                                  step: 8,
                                  branch_type: "upper_trunk",
                                  ppl: 3,
                                  time: 10,
                                  type: "pax_local_db",
                                  children: [
                                    {
                                      name: "d3 local",
                                      step: 11,
                                      branch_type: "uppest_trunk",
                                      ppl: 1,
                                      time: 50,
                                      type: "prog",
                                      children: [
                                        {
                                          name: "Map",
                                          step: 12,
                                          branch_type: "leaf",
                                          ppl: 1,
                                          time: 10,
                                          type: "vis",
                                          link: "https://www.peaceagreements.org/visualizations/local-agreements/"
                                        },
                                      ],
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                        {
                          name: "Code",
                          step: 6,
                          branch_type: "upper_trunk",
                          ppl: 2,
                          time: 100,
                          type: "paax_code",
                          children: [
                            {
                              name: "Quality Control",
                              step: 7,
                              branch_type: "upper_trunk",
                              ppl: 7,
                              time: 20,
                              type: "paax_quality_control",
                              children: [
                                {
                                  name: "PAA-X",
                                  step: 8,
                                  branch_type: "upper_trunk",
                                  ppl: 1,
                                  time: 10,
                                  type: "paax_db",
                                  children: [
                                    {
                                      name: "VUE",
                                      step: 11,
                                      branch_type: "uppest_trunk",
                                      ppl: 1,
                                      time: 50,
                                      type: "prog",
                                      children: [
                                        {
                                          name: "Actors-Network",
                                          step: 12,
                                          branch_type: "leaf",
                                          ppl: 1,
                                          time: 10,
                                          type: "vis",
                                          link: "https://www.peaceagreements.org/visualizations/actor-networks/"
                                        },
                                      ],
                                    },
                                    {
                                      name: "d3",
                                      step: 11,
                                      branch_type: "uppest_trunk",
                                      ppl: 1,
                                      time: 50,
                                      type: "prog",
                                      children: [
                                        {
                                          name: "3rd Party Scroll",
                                          step: 12,
                                          branch_type: "leaf",
                                          ppl: 3,
                                          time: 10,
                                          type: "vis",
                                          link: "https://www.peaceagreements.org/visualizations/third-party-scroll/"
                                        },
                                      ],
                                    },
                                    {
                                      name: "Python",
                                      step: 11,
                                      branch_type: "uppest_trunk",
                                      ppl: 1,
                                      time: 50,
                                      type: "prog",
                                      children: [
                                        {
                                          name: "Network",
                                          step: 12,
                                          branch_type: "leaf",
                                          ppl: 1,
                                          time: 10,
                                          type: "vis",
                                        },
                                      ],
                                    },
                                    {
                                      name: "Tracker Development",
                                      step: 11,
                                      branch_type: "uppest_trunk",
                                      ppl: 1,
                                      time: 50,
                                      type: "prog",
                                      children: [
                                        {
                                          name: "Tracker",
                                          step: 12,
                                          branch_type: "leaf",
                                          ppl: 3,
                                          time: 50,
                                          type: "vis",
                                          link: "https://www.peaceagreements.org/tracker/"
                                        },
                                      ],
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },

                        {
                          name: "d3",
                          step: 13,
                          branch_type: "uppest_trunk",
                          ppl: 3,
                          time: 50,
                          type: "prog",
                          children: [
                            {
                              name: "Messy Timeline",
                              step: 14,
                              branch_type: "leaf",
                              ppl: 3,
                              time: 10,
                              type: "vis",
                              link: "https://www.peaceagreements.org/visualizations/messy-peace-processes/"
                            },
                          ],
                        },
                        {
                          name: "d3",
                          step: 13,
                          branch_type: "uppest_trunk",
                          ppl: 5,
                          time: 50,
                          type: "prog",
                          children: [
                            {
                              name: "Time & Space",
                              step: 14,
                              branch_type: "leaf",
                              ppl: 5,
                              time: 10,
                              type: "vis",
                              link: "http://peaceagreements.org/visualizations/agreements-process-map/"
                            },
                          ],
                        },
                        {
                          name: "d3",
                          step: 13,
                          branch_type: "uppest_trunk",
                          ppl: 1,
                          time: 50,
                          type: "prog",
                          children: [
                            {
                              name: "Sequence Comparison",
                              step: 14,
                              branch_type: "leaf",
                              ppl: 1,
                              time: 50,
                              type: "vis",
                              link: "https://www.peaceagreements.org/visualizations/compare-processes/"
                            },
                          ],
                        },
                        {
                          name: "d3",
                          step: 13,
                          branch_type: "uppest_trunk",
                          ppl: 2,
                          time: 50,
                          type: "prog_overview",
                          children: [
                            {
                              name: "Data Overview",
                              step: 14,
                              branch_type: "leaf",
                              ppl: 2,
                              time: 50,
                              type: "vis",
                              link: "https://www.peaceagreements.org/visualizations/data-overview-visualization/"
                            },
                          ],
                        },
                        {
                          name: "Infographics",
                          step: 15,
                          branch_type: "leaf",
                          ppl: 3,
                          time: 10,
                          type: "pdf",
                          link: "",
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};